### ISSUE TITLE
Feature parity with terraform-provider-cloudfoundry

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-community/terraform-provider-cf#12]
The following data sources are missing in order to reach feature parity with [terraform-provider-cloudfoundry](https://github.com/orange-cloudfoundry/terraform-provider-cloudfoundry/):
- Config (feature-flags)
- App
- Route
- Service broker
- Service binding

**Comment by ArthurHlt** [comment]
this is now the case with #203
