### ISSUE TITLE
Rearchitecture provider to leverage CF V3 client library (possibly CF CLI internal API)

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-community/terraform-provider-cf#120]
The CF CC API is complex and sometimes not very well documented. In addition, the V3 api bring lots of changes and low level control. Implementing a CC API client is large effort (that we touch on in various workflows such as cf_app provision or update). We should reconsider leveraging existing CF API client.

The https://github.com/orange-cloudfoundry/terraform-provider-cloudfoundry/ took the approach of wrapping the CF CLI internal API.

The CF CLI internal API isn't yet client friendly, and may need some feedback.

This relates to #56

**Comment by gberche-orange** [comment]
@ArthurHlt could you provide return on experience from https://github.com/orange-cloudfoundry/terraform-provider-cloudfoundry/ and potentially provide guidance/prototype/suggestions on how to reuse CF CLI for a v2 of mevansam/terraform-provider-cf ?

**Comment by gberche-orange** [comment]
[CC API V2 deprecation draft plan](https://docs.google.com/document/d/1KFZogeeexOqFf13oKHloe2QAorLh9OqwQHp8JvBl9lY/edit) has been published. A 6 month overlap is planned by the time the CF CLI is not using CC API V2 anymore.

**Comment by gberche-orange** [comment]
Given the fact that CF started supporting server-side manifest, and that some features such as istio are considered to only be added through manifest syntax (i.e. without specific CF CLI command nor even specific CC API endpoint), I wonder whether it would make sense for parts of the `mevansam/terraform-provider-cf` resources implementation to rendered into a generated `manifest.yml` and just delegate a call to the latest v3 (zero-downtime) `cf push -f GENERATED_TMP_MANIFEST_PATH` 

Following are more details related to server-side manifest.

[Server side app manifest](https://docs.google.com/document/d/1JBWFP86t5mgu7_Cie97AIDlsFGyHIGsfJb3kmcNtHZE/edit?ts=5a58115a) - [cf-dev@ thread](https://lists.cloudfoundry.org/g/cf-dev/message/7649?p=,,,20,0,0,0::Created,,proposal+to+move+app+manifest+processing+logic+to+a+server+side+API,20,2,0,8011437) [epic](https://www.pivotaltracker.com/epic/show/3867153)
   - [API proposal](https://docs.google.com/document/d/1fxp2lhT_SIxXXrjJJg2cN6ADHxZdkzyb5zHdQAwQtyI/edit#)
   - [Existing V2 behaviors](https://docs.google.com/document/d/1Qv-svQXy4VzGcfYsAEY3lPGMJMFl3ChKha9Uf_kmG6k/edit)
   - [V3 Server-Side Multi-App Manifests Proposal](https://docs.google.com/document/d/1z-0Ev-QCtuoT8nJCoNaVJmkMPNk4PYi_VGWzc8CwBIs/edit#) - Started [Epic](https://www.pivotaltracker.com/epic/show/4112079) [api doc](http://v3-apidocs.cloudfoundry.org/version/3.69.0/index.html#space-manifest)

@ArthurHlt Any feedback ? Is it something you had already considered/prototyped with in [orange-cloudfoundry/terraform-provider-cloudfoundry/](https://github.com/orange-cloudfoundry/terraform-provider-cloudfoundry/) ?

**Comment by gberche-orange** [comment]
Concerns expressed by @jcarrothers-sap related to using server side manifest during weekly meeting on May 6th, which invalidate the approach of using server-side manifests

http://v3-apidocs.cloudfoundry.org/version/3.68.0/index.html#apply-an-app-manifest
```
Apply changes specified in a manifest to an app and its underlying processes. 
These changes are additive and will not modify any unspecified properties or 
remove any existing environment variables, routes, or services.
```

Besides, @ArthurHlt noticed CF CLI internal API is now much more friendly, and potentially much simpler to use now: see https://github.com/cloudfoundry/cli/tree/master/api 

Also this might help reduce/shrink the codebase in the provider (in addition to help migrate to v3 api)

**Comment by ArthurHlt** [comment]
#203 handle call to api v3 but also nooaa for retrieving app logs and policy cli client for policy network.

I'm closing it
