### ISSUE TITLE
Leverage standard cf apps for tests 

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-community/terraform-provider-cf#123]
This is a followup of @janosbinder 's question on #118

> I have created a fork, to mimic a new version of an app (see https://github.com/mevansam/terraform-provider-cf/blob/7c92a2be65993f6b73ab709e273bc03902dd1a81/cloudfoundry/resource_cf_app_test.go#L281 ) Let me know how do we want to keep our test apps in github.

The codebase currently relies on a set of external repos 

```
grep -r "https://github.com" cloudfoundry/ | grep url
cloudfoundry/resource_cf_buildpack_test.go:             url = "https://github.com/cloudfoundry-community/tomee-buildpack"                               
cloudfoundry/resource_cf_route_service_binding_test.go: url := "https://github.com/benlaplanche/cf-basic-auth-route-service.git"
cloudfoundry/resource_cf_route_test.go:         url = "https://github.com/mevansam/test-app.git"
cloudfoundry/resource_cf_route_test.go:         url = "https://github.com/mevansam/test-app.git"
cloudfoundry/resource_cf_route_test.go:         url = "https://github.com/mevansam/test-app.git"
cloudfoundry/resource_cf_route_test.go:         url = "https://github.com/mevansam/test-app.git"
cloudfoundry/resource_cf_app_test.go:   url = "https://github.com/mevansam/spring-music/releases/download/v1.0/spring-music.war"
cloudfoundry/resource_cf_app_test.go:   url = "https://github.com/mevansam/spring-music/releases/download/v1.0/spring-music.war"
```

This may cause the following issues:
- these repos might be deleted by errors
- changes in these repos might break etsts (as the git url pulls the HEAD instead, and not yet a specific commit as the CF CLI allows for buildpack git urls
- these repos might need maintenance to account for buildpack changes.

```
$cf push --help
[...]
cf push APP_NAME [-b BUILDPACK_NAME]
   -b                           Custom buildpack by name (e.g. my-buildpack) or Git URL (e.g. 'https://github.com/cloudfoundry/java-buildpack.git') or Git URL with a branch or tag (e.g. 'https://github.com/cloudfoundry/java-buildpack.git#v3.3.0' for 'v3.3.0' tag).
```

Potential improvements:
- consider leveraging instead community maintained sample apps, such as [https://github.com/cloudfoundry/cf-smoke-tests](https://github.com/cloudfoundry/cf-smoke-tests/tree/master/assets) (currently weighting 17MB) with ruby app support
- consider adding support for git commit hash in git resource (possibly as part of #58)

**Comment by ArthurHlt** [comment]
We use a dummy app set inside this repo, all external has been removed. This is the same for broker
