### ISSUE TITLE
Refactor tests so they don't rely on PCFDev services whose instabilities break the tests

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-community/terraform-provider-cf#141]
Many of services related tests rely on availability of PCFDev services in the marketplace, causing the following issues:
- in the acceptance environment, some services have been instable and broken tests:
```
$ cf s
Getting services in org pcfdev-org / space pcfdev-space as admin...

name   service   plan          bound apps   last operation
test   p.redis   cache-small                delete failed
$ cf ds -f test
Deleting service test in org pcfdev-org / space pcfdev-space as admin...
FAILED
Server error, status code: 502, error code: 10001, message: Service instance test: The service broker could not be reached: http://192.168.8.31:12345/v2/service_instances/037ff464-a725-467d-8ee0-7502292651ca?accepts_incomplete=true&plan_id=05491E77-4B47-49D3-97FE-3E8E2B02F905&service_id=13560975-3F2C-44E8-B1F4-FDADF89CCB93
```

- this makes it more difficult to run acceptance tests in a pure OSS CF deployment where these services might be missing

A possible solution is instead to use stubbed services leveraging the [CATS Async broker](https://github.com/cloudfoundry/cf-acceptance-tests/tree/master/assets/service_broker) which is vendored into https://github.com/mevansam/terraform-provider-cf/tree/dev/tests/cf-acceptance-tests and can be pushed as a cf app using terraform as test fixtures such as in the following, or in the [scripts/prepare-tfacc-env.sh](https://github.com/mevansam/terraform-provider-cf/blob/dev/scripts/prepare-tfacc-env.sh) script

https://github.com/mevansam/terraform-provider-cf/blob/e171a185ec782c3fddd31f34573de991999b5c48/cloudfoundry/resource_cf_service_instance_test.go#L81-L102

**Comment by gberche-orange** [comment]
@mevansam following your PR #186 can you confirme the `TEST_SERVICE_*` references are now obsolete can can be removed ? 

https://github.com/mevansam/terraform-provider-cf/blob/8692b4ee40c7bcbb4aa0e85a8751b780d6129c78/scripts/prepare-tfacc-env.sh#L51-L58

https://github.com/mevansam/terraform-provider-cf/blob/fe1871627f8329b7a5090ca9f317510b2a2b7652/cloudfoundry/provider_test.go#L199-L237

**Comment by ArthurHlt** [comment]
This is still required but only related to cats service broker. 
I'm closing it has technical-debt here has been addressed
