### ISSUE TITLE
Rename repo from terraform-provider-cf to terraform-provider-cloudfoundry

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-community/terraform-provider-cf#146]
along with #85 we should probably rename the repo before transfering ownership to https://github.com/terraform-providers/ as part of #38, and change the name of the binaries produced as to avoid user confusion when installing them.

Trying to do so locally fails with the following message
```
make build
go install
# github.com/terraform-providers/terraform-provider-cloudfoundry
./main.go:10:15: cannot use cloudfoundry.Provider (type func() "github.com/terraform-providers/terraform-provider-cf/vendor/github.com/hashicorp/terraform/terraform".ResourceProvider) as type "github.com/terraform-providers/terraform-provider-cloudfoundry/vendor/github.com/hashicorp/terraform/plugin".ProviderFunc in field value
GNUmakefile:14: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by ashald** [comment]
FWIW, this plugin is now available via [`para` Terraform community plugin manager](https://github.com/paraterraform/para) as `cloudfoundry` - https://github.com/paraterraform/index/commit/894c9ca70071b3561c3949c70f95e6cf144a58e8
