### ISSUE TITLE
Wrong CF application is updated

### ISSUE THREAD

**Issue by lextiz** [cloudfoundry-community/terraform-provider-cf#166]
[Here](https://github.com/mevansam/terraform-provider-cf/blob/master/cloudfoundry/cfapi/app_manager.go#L112) the applications are being queried by name only, not including space. This means if 2 different spaces have the apps with the same names a random one will be fetched by application manager. This can cause behaviors that are hard to troubleshoot.

**Comment by janosbinder** [comment]
Thank you for your report @lextiz . So you mean if we have _space1_ and _space2_ deployed in a CF space and we have two applications named _myapp_ deployed in  _space1_ *and* in _space2_ then the _findApp_ in the application manager could report ambiguous results. Please let me know whether this is the case.

**Comment by lextiz** [comment]
Yes, this is the case. I have manually validated the issue by running "cf curl". Adding additional query with space id fixes the issue.

**Comment by jcarrothers-sap** [comment]
@lextiz Just to confirm, have to experienced the provider actually doing the wrong thing, or is this just a code analysis bug?  As best I can tell, the method in question (`FindApp`) is currently only used by the testing code.

**Comment by lextiz** [comment]
I have experienced the problem on the [fork of this repo](https://github.com/chrismathias/terraform-provider-cf), that actually uses this function, tracked the root cause and saw that the upstream has the bug as well, so I found it important to inform you about the bug, because if the function will be used this would become  severe issue and break isolation between spaces.

**Comment by gberche-orange** [comment]
@lextiz looking back into this issue, I could not see the corresponding code at being used other than in tests, see related [github code search](https://github.com/mevansam/terraform-provider-cf/search?q=FindApp&unscoped_q=FindApp) https://github.com/mevansam/terraform-provider-cf/blob/f03f28fe8a8c73db847275ff716da1f1a0e71da1/cloudfoundry/cfapi/app_manager.go#L109-L126

Are you able to reproduce and provide a test case to reproduce it (e.g. with two apps named the same in distinct spaces) ?

Thanks again for your report.

**Comment by lextiz** [comment]
Hi @gberche-orange, this issue is not in my priority list and has an easy workaround (attaching a different prefix to each space) so I am not planning to write a test for it, sorry. Regarding reproducing the issue: in case the code did not change I would guess it is still reproducible.

**Comment by ArthurHlt** [comment]
Please check new release at https://github.com/cloudfoundry-community/terraform-provider-cf/releases/tag/v0.10.0 to see if it fix your issue.
I'm closing it for now, please re-open if you still found on issue on this.
