### ISSUE TITLE
cf_service_broker lacks a way to refresh service catalog without deleting the resource

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-community/terraform-provider-cf#170]
As an Cf operator, when a service broker refreshes its catalog, I need a way to trigger an update of the service broker through terraform. Using a [terraform taint](https://www.terraform.io/docs/commands/taint.html) is not suiteable since this will be forcing the servicer broker to be destroyed and recreated on the next apply (and likely delete all nested service instances).

See related code at https://github.com/mevansam/terraform-provider-cf/blob/dev/cloudfoundry/resource_cf_service_broker.go

https://github.com/orange-cloudfoundry/terraform-provider-cloudfoundry#service-brokers computes and stores a hash of the service catalog in order such need to update the service broker

@ArthurHlt @psycofdj Is it something you could consider porting to `mevansam/terraform-provider-cf`?

Relates to #12

**Comment by psycofdj** [comment]
This is a short term need for us and we're willing to contribute on this.

We'll have to think carefully about corner cases where `cloudfoundry_service_access` resources are targeting a plan being deleted on the catalog update.

**Comment by ArthurHlt** [comment]
Please check new release at https://github.com/cloudfoundry-community/terraform-provider-cf/releases/tag/v0.10.0 to see if it fix your issue.
I'm closing it for now, please re-open if you still found on issue on this.
