### ISSUE TITLE
Release 0.10.0

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-community/terraform-provider-cf#176]
The team agreed to have consensus on when to cut such release through a github issue.

The pending changes are now documented into https://github.com/mevansam/terraform-provider-cf/blob/dev/CHANGELOG.md

Please comment this issue to indicate whether you'd like to merge additional contributions before this release is cut, or whether you have detected yet unreported regressions that would deserve more investigation.

**Comment by psycofdj** [comment]
Ok for me.
We can probably merge #169 for this release.

**Comment by janosbinder** [comment]
Adding https://github.com/mevansam/terraform-provider-cf/pull/171 as it is a fix. Let me, whether you intend to have https://github.com/mevansam/terraform-provider-cf/pull/174 in this release or in <0.10.0?

**Comment by ArthurHlt** [comment]
I would like to include #203 on this release which can be considered has an heavy version

**Comment by ScottGuymer** [comment]
Any ideas when this version will be released?

**Comment by ArthurHlt** [comment]
@ScottGuymer we don't have a precise date but we had to validate migration between current provider and changes introduced in #203 . We have validated this just this week and we need to update the documentation.

Next release will be released soon, we have to talk first with other committers to agreed on a release date

**Comment by ArthurHlt** [comment]
New version 0.10.0 has been released \o/
