### ISSUE TITLE
Unable to create service-key with params of type bool

### ISSUE THREAD

**Issue by eloo** [cloudfoundry-community/terraform-provider-cf#189]
Hi,
currently i'm trying to create a service key with a parameter with value type bool but i'm unable to get it working. Maybe i missed some thing or this could be a bug? i'm trying to create it like this: 
```
resource "cloudfoundry_service_key" "my_key" {
  name = "my_key"
  service_instance = "${cloudfoundry_service_instance.my_service.id}"
  params = {
        "BooleanValueExpected" = true
  }
}
```
this leads to an error like this 
```
cloudfoundry_service_key.my_key: Server error, status code: 502, error code: 10001, message: Service broker error: json: cannot unmarshal string into Go struct field BindParameters.BooleanValueExpected of type bool
```

Any ideas? Or is someone else facing this issue? 
Thx for your help

Edit:
The output of the apply looks like this:
```
cloudfoundry_service_key.my_key: Creating...
  credentials.%:        "" => "<computed>"
  name:                 "" => "my_key"
  params.%:             "" => "1"
  params.BooleanValueExpected: "" => "1"
  service_instance:     "" => "ea456055-3070-47d5-a890-f9f53e87a85e"
```

**Comment by janosbinder** [comment]
Hi, could you pass the boolean value as string?

`"BooleanValueExpected" = "true"`

If it works, please close the case.

**Comment by eloo** [comment]
@janosbinder 
nope this the same issue :/

**Comment by gberche-orange** [comment]
thanks @eloo for reporting this issue. Sorry the team of volunteers has not sufficient resources to further reproduce and diagnose the issue.

Current test case includes multiple keys:

https://github.com/mevansam/terraform-provider-cf/blob/fe1871627f8329b7a5090ca9f317510b2a2b7652/cloudfoundry/resource_cf_service_key_test.go#L33-L41

Can you please try to see if you're reproducing the problem when adding a second (unrelated/extra) field ?

**Comment by eloo** [comment]
@gberche-orange 
but it looks like none of the values is a boolean. so i guess this wouldn't cover the issue?

**Comment by gberche-orange** [comment]
@eloo just made the test with

```hcl
resource "cloudfoundry_service_key" "my_mysql_key" {
  name = "my_mysql_key"
  service_instance = "${cloudfoundry_service_instance.my_mysql.id}"
  params {
    "key1" = "aaaa"
//    "key2" = "bbbb"
    "key3" = "true"
  }
}
```

and it provisionned successfully

```diff
 + cloudfoundry_service_key.my_mysql_key
      id:               <computed>
      credentials.%:    <computed>
      name:             "my_mysql_key"
      params.%:         "2"
      params.key1:      "aaaa"
      params.key3:      "true"
      service_instance: "7cd18a0c-ebe0-497d-bd17-985c50c4b81a"


Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

cloudfoundry_service_key.my_mysql_key: Creating...
  credentials.%:    "" => "<computed>"
  name:             "" => "my_mysql_key"
  params.%:         "" => "2"
  params.key1:      "" => "aaaa"
  params.key3:      "" => "true"
  service_instance: "" => "7cd18a0c-ebe0-497d-bd17-985c50c4b81a"
cloudfoundry_service_key.my_mysql_key: Creation complete after 3s (ID: ef24bb83-921f-40b8-9379-75db76a5ff93)
```

I hope this could potentially be useful as a workaround

**Comment by eloo** [comment]
@gberche-orange 
a okay.. and key3 is type of bool in the service broker?

**Comment by gberche-orange** [comment]
@eloo the service broker used in my tests just ignores params. 

Are you sure the `cannot unmarshal string into Go struct field BindParameters.BooleanValueExpected of type bool` error trace does not come from your service broker instead (especially as I did not find parsing of the json in the provider) ?

**Comment by gberche-orange** [comment]
@eloo testing again with a single boolean param, the provider completes without error

```hcl
resource "cloudfoundry_service_key" "my_mysql_key" {
  name = "my_mysql_key"
  service_instance = "${cloudfoundry_service_instance.my_mysql.id}"
  params {
    "key3" = "true"
  }
}
```

```
cloudfoundry_service_key.my_mysql_key: Creating...
  credentials.%:    "" => "<computed>"
  name:             "" => "my_mysql_key"
  params.%:         "" => "1"
  params.key3:      "" => "true"
  service_instance: "" => "d6cf5ef8-2ead-4079-806c-d8f0dfe35d69"
cloudfoundry_service_key.my_mysql_key: Creation complete after 2s (ID: 099b72b0-a47c-40ad-94db-fd02e2efc47a)
```

**Comment by eloo** [comment]
i'm pretty sure that this error comes from the service broker.
It looks like the problem is that a string is passed from the terraform provider to the servicebroker instead of a boolean.. 
the tf provider is doing some conversion for example from true to "1" which leads to the error.. for example using plain cf cli i see the following behaviour
```
cf create-service-key my-service test -c '{"booleanKey": true}'
> OK

cf create-service-key my-service test2 -c '{"booleanKey": "1"}'
> Service broker error: json: cannot unmarshal string into Go struct field BindParameters.AccessMetrics of type bool
```

**Comment by gberche-orange** [comment]
Right, Sorry about my confusion, got confused with https://github.com/mevansam/terraform-provider-cf/issues/189#issue-424950266 which shows `  params.BooleanValueExpected: "" => "1"`

Which version of terraform and the provider are you running ?

To be able to reproduce this problem,  I can see the following approaches:
- trace https request sent to cloudcontroller in the provider. Submitted related #197 
- trace http request received by the broker. https://github.com/mevansam/terraform-provider-cf/blob/dev/tests/cf-acceptance-tests/assets/service_broker/service_broker.rb#L145-L161 might help

**Comment by ArthurHlt** [comment]
Please check new release at https://github.com/cloudfoundry-community/terraform-provider-cf/releases/tag/v0.10.0 to see if it fix your issue.
I'm closing it for now, please re-open if you still found on issue on this.

**Comment by eloo** [comment]
Looks like this is still not working with version 0.11

**Comment by eloo** [comment]
at least its working with params_json like this
```
  params_json = "{\"MyBoolean\": true}"
```
