### ISSUE TITLE
enhance cloudfoundry_app to detect changes in unversionned app sources/binaries content

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-community/terraform-provider-cf#195]
Currently, changes to unversionned app sources/binaries content are not detected, eg.
- `url` whose content change without url changing
- `git` without tag or branch change whose remote repo change 
- `docker_image` without tag or branch change whose remote latest image change 

A possible enhancement would be to store a hash of the content and compare it to detect this change.

See https://github.com/orange-cloudfoundry/terraform-provider-cloudfoundry/blob/52f6d35199aa6091066b1938d6585004bb416a4e/resources/apps.go#L770-L777 contributed by @ArthurHlt  for inspiration

Reported by @abendt in https://cloudfoundry.slack.com/archives/C7JRBR8CV/p1556530514015000?thread_ts=1556291839.012200&cid=C7JRBR8CV

As a workaround, currently users manually control version changes by bumping version in artifact urls.  A Datasource or script to lookup latest version of an artifact might be able to help automate this for the case of a CI/CD.

Relates to #12

**Comment by gberche-orange** [comment]
Proposal by @ArthurHlt to instead spawn out the app artefact out of the resource.

See related https://github.com/ArthurHlt/terraform-provider-zipper#usage and #58

**Comment by ArthurHlt** [comment]
This proposal has been implemented in #203
