### ISSUE TITLE
Support application binding to service with complex params 

### ISSUE THREAD

**Issue by abendt** [cloudfoundry-community/terraform-provider-cf#199]
Context
--------

while binding my service to a database i need to pass in some extra configuration.
using the CF cli i can do: _cf bind-service app my_database -c ’{“ConnectionParams”: {“sslmode”: “require” }}’_.

Problem
--------

this does not seem to be possible with TF:

when trying to use nested maps we get an error from within TF
```
  service_binding {
    service_instance = "${cloudfoundry_service_instance.db.id}"

    params {
      ConnectionParams {
        sslmode =  "require"
    }
  }

Error: cloudfoundry_app.sba-cl: service_binding.0.params (ConnectionParams): '' expected type 'string', got unconvertible type '[]map[string]interface {}'
```

when trying to partially build params with string it ends up generating wrong JSON causing a n error in CF
```
service_binding {
    service_instance = "${cloudfoundry_service_instance.db.id}"

    // [1]
    params { 
      ConnectionParams = <<JSON
{sslmode = "require"}JSON
    }
  }

JSON body: {"app_guid":"9290c3d4-0b2a-4a89-913f-94f884f3d6ae","parameters":{"ConnectionParams":"{sslmode = require}"},"service_instance_guid":"9753e48a-3403-4a94-9538-328add772469"} [2]
```

[1] we tried some variations here to construct params. see the slack discussion for more details: https://cloudfoundry.slack.com/archives/C7JRBR8CV/p1556637470019200

[2] for the JSON output i patched the plugin locally and added some debug output: https://github.com/mevansam/terraform-provider-cf/blob/master/cloudfoundry/cfapi/app_manager.go#L519

**Comment by gberche-orange** [comment]
thanks @abendt and @nakulvr for reporting this issue and attempted workarounds. 

Indeed currently the binding params is a [TypeMap](https://www.terraform.io/docs/extend/schemas/schema-types.html#typemap) which according to  [schema.go documentation](https://github.com/hashicorp/terraform/blob/133d3d79714077d8009e35759ac7dad18522e6b6/helper/schema/schema.go#L195-L203) only support storing primitive types

> // Elem represents the element type. For a TypeMap, it must be a *Schema
> // with a Type that is one of the primitives: TypeString, TypeBool,
> // TypeInt, or TypeFloat.

https://github.com/mevansam/terraform-provider-cf/blob/fb727780487b3d352ab82e5835887a3aae8ab179/cloudfoundry/resource_cf_app.go#L214-L217

This seems very similar to https://github.com/mevansam/terraform-provider-cf/pull/24 contributed by @psycofdj for user-provided-service. Similar support exists for service_instance:

https://github.com/mevansam/terraform-provider-cf/blob/fb727780487b3d352ab82e5835887a3aae8ab179/cloudfoundry/resource_cf_service_instance.go#L48-L52

A contribution to bring a similar solution with a distinct attribute with serialized json string to service binding params would be much welcome.

**Comment by janosbinder** [comment]
Could this PR be extended to support https://github.com/mevansam/terraform-provider-cf/pull/92 ?

**Comment by abendt** [comment]
@gberche-orange i have added an extra _params_json_ parameter here: https://github.com/mevansam/terraform-provider-cf/pull/200

looking forward for feedback

**Comment by gberche-orange** [comment]
thanks @abendt

Would you be interested in being added as a contributor to the repo if you're planning to contribute other features/fixes ? 

This would speed up feedback cycles, see https://github.com/mevansam/terraform-provider-cf/blob/dev/CONTRIBUTING.md#contributing-new-features

**Comment by abendt** [comment]
i have nothing planned right now, it really depends on the needs of the project i am currently working on. 
i am still quite new to CF/TF and think the feedback cycle with PR's is working good for me.
if it turns out we have more features to add and i get more experience with the codebase this might change. 
So i would suggest we wait until a couple of my PR's are released and then check in again.

**Comment by ArthurHlt** [comment]
You will found new attribute `params_json` in PR #203 does this handle your issue ?
Terraform 0.12 is needed to test this attribute

**Comment by ArthurHlt** [comment]
Please check new release at https://github.com/cloudfoundry-community/terraform-provider-cf/releases/tag/v0.10.0 to see if it fix your issue.
I'm closing it for now, please re-open if you still found on issue on this.
