### ISSUE TITLE
User GUID for public providers

### ISSUE THREAD

**Issue by archgrove** [cloudfoundry-community/terraform-provider-cf#2]
It seems public providers (e.g. Pivotal's public offering) don't allow end users to call `/v2/users`. As such, the `cf_user` datasource doesn't work. This means one cannot get the GUID of a user for use in, e.g., `cf_space` role assignment.

A resource that allows the lookup of a user by name within an organisation might be helpful to solve this?

**Comment by gberche-orange** [comment]
@archgrove Would be worth weighting a new 'cf_org_user' data source w.r.t. an update to the existing [cf_user](https://github.com/mevansam/terraform-provider-cf/blob/master/website/docs/d/user.html.markdown) data source with an additional optional `org` argument. When using the `org` argument, the data source would act similarly to the `cf org-users` CLI command (and likely to leverage the same api calls)

```hcl
data "cf_user" "myuser" {
    name = "myuser"    
    org="my_org"
}
```

The associated documentation could then become

> The following arguments are supported:
> *    name - (Required) The name of the user to look up
> *    org - (Optional, String) The GUID of the Org into which the user is declared. This is useful when the account used in this provider is not granted access to all users in cloudfoundry
>

**Comment by archgrove** [comment]
@gberche-orange I'd be happy to have a go at this, but I'm not sure how to persuade the CloudController API to filter org users by name. I can certainly implement it by getting all users and post-hoc filtering that, but it seems more efficient to filter the call to `/v2/organizations/:guid/users`. However, attempts to filter by `username` fail. This seems odd, but may be a limit of the CC API?

**Comment by gberche-orange** [comment]
@archgrove 
> However, attempts to filter by username fail. This seems odd, but may be a limit of the CC API?

http://apidocs.cloudfoundry.org/280/organizations/list_all_users_for_the_organization.html

does not seem to document a support userid filter, so post filtering seems necessary.

The CF CLI does not support an equivalent endpoint, so the closest in CF API seems org: https://github.com/mevansam/terraform-provider-cf/blob/fae0e6782258c4e0e862ffb708341ce2585f171b/vendor/code.cloudfoundry.org/cli/cf/api/users.go#L111-L113 which would need to iterate into each role, and seems adding unnecessary complexity.

**Comment by archgrove** [comment]
Phew, thought I was going mad. I'll try and find time to have a pass at this soon. Thanks!

**Comment by gberche-orange** [comment]
@archgrove Any feedback on the proposal above ?

We had discussion on modifying the cf_space resource to support user name in addition to user guid. However, it seem the user name is a mutable field according to uaa API http://docs.cloudfoundry.org/api/uaa/version/4.8.0/index.html#create-4 So we'd rather stick to the proposal above with cf_user data source refinement

**Comment by archgrove** [comment]
@gberche-orange I've been looking at this, but one of our providers (IBM Bluemix) seems to not be honouring the CF API contract - usernames are not coming back in calls to `/v2/organizations/:guid/users`. I'm investigating whether this is permissible behaviour (and so this approach won't really work), or just IBM being broken (again).

**Comment by archgrove** [comment]
I've been chatting with the CAPI team at Pivotal. Apparently, it's not entirely out of spec for that endpoint to not include usernames. If UAA doesn't contain them, then the API won't return them. Why IBM have this setup this way, I don't know - but it makes doing something robust to all provider configurations a problem.

**Comment by gberche-orange** [comment]
@archgrove The IBM bluemix set up is unsual, as execution of the `cf org-users` command currently returns a list of empty blank lines. As you mentionned, I guess this is linked to the way the BlueMix UAA is connected with their SAML backend. 

So such contrib would still be applicable to most public CF providers. I validated the cf org-users works correctly with PWS, Swisscloud, and SAP.

Feel free to submit a PR if you can.

ps: this is unsatisfatory, but I'm working around the issue on pws by specifying the userguid, which I obtain from the CF CLI:

```
CF_TRACE=true cf org-users my-org | grep -B10 '"username": "myuser@mydomain.com"' | grep '"guid"'
```

**Comment by ArthurHlt** [comment]
I don't think we can do anything for this. For now simply avoid resource/datasource which manipulate user object is recommended. I'm closing because I can't found better solution for now
