### ISSUE TITLE
WaitForAppToStart only waits for 1 instance of the application to be running

### ISSUE THREAD

**Issue by tgpo-sap** [cloudfoundry-community/terraform-provider-cf#207]
From:
https://github.com/cloudfoundry-community/terraform-provider-cf/blob/master/cloudfoundry/cfapi/app_manager.go#L363
https://apidocs.cloudfoundry.org/9.2.0/apps/get_detailed_stats_for_a_started_app.html

Apparently `WaitForAppToStart` only waits for 1 instance of the application to be running. However, there could be cases when the nth instance may fail. In this case, the proposal is to do a for loop check on all instances or count the total running of instances before accepting the application is fully running.

**Comment by ArthurHlt** [comment]
We actually mimic the cli on this. `cf push` only wait for one instance, maybe a parameter to set at true for waiting all instances on the resource could do the job. But for now, I don't see case for doing this. Maybe if other users report the need (I don't understand if sap really needs it or it can be just useful) we can implement this. For now, I'm closing it. Feel free to re-open
