### ISSUE TITLE
Bad construction of fragment when migrating to rework-back

### ISSUE THREAD

**Issue by psycofdj** [cloudfoundry-community/terraform-provider-cf#211]
https://github.com/cloudfoundry-community/terraform-provider-cf/blob/70c95bb357c75485dacab1507e939a5f66fbbe5f/cloudfoundry/migrate_bits.go#L272-L274

When migrating provider from dev branch to rework-back, the provider seems to search for `refs/tags/masterv2.0.1`. 

My guess is that the current state refers to an unsued attribute 'branch' with default value of `master`, and the migrate_bits use it to construct the unknown reference `masterv2.0.1`

**Comment by ArthurHlt** [comment]
thanks for the catch, this has been fixed.

btw, docker hub has been triggered but not pushed in our local registries
