### ISSUE TITLE
no integrity check wrt routes/domain

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry-community/terraform-provider-cf#213]
When a domain declaration is removed, the terraform cf plugin does not check routes existence on cf, and just removes domain + all routes. This is un reliable, and error prone

cc @gberche-orange

**Comment by ArthurHlt** [comment]
We mimic cli behaviour as cli does not check before removing (Actually, we simply call delete order on the API and cf delete routes by itself). It only ask confirmation, which terraform does too when doing plan or apply.

I'm closing it as behaviour is correct on provider.
