### ISSUE TITLE
0.10.0 wipes docker credentials upon app update

### ISSUE THREAD

**Issue by sleungcy** [cloudfoundry-community/terraform-provider-cf#220]
*Version* 0.10.0
*Pre-requisite* A private docker image created on CF using this v0.10.0 plugin. The private docker repo url along with credentials are provided to CF.
*Problem* When updating a docker application using bluegreen stragey, the credentials are completely removed, then fails to retrieve the docker image.

My suspicion is that the the copy_bits operation is wiping out all the specified credentials. Perhaps CopyApp should be skipped for docker applications.

**Comment by janosbinder** [comment]
Fixed by https://github.com/cloudfoundry-community/terraform-provider-cf/pull/222
