### ISSUE TITLE
Support SSO authentication

### ISSUE THREAD

**Issue by vixus0** [cloudfoundry-community/terraform-provider-cf#226]
Some Cloud Foundry deployments make use of single sign on (SSO) authentication using a passcode:

```
   cf login [-a API_URL] [-u USERNAME] [-p PASSWORD] [-o ORG] [-s SPACE] [--sso | --sso-passcode PASSCODE]
   cf login --sso (cf will provide a url to obtain a one-time passcode to login)
   --sso                      Prompt for a one-time passcode to login
   --sso-passcode             One-time passcode
```

The provider currently doesn't support this authentication flow, and also attempts to login multiple times (in the refresh and plan steps, for example).

**Comment by ArthurHlt** [comment]
Thanks for your implementation
