### ISSUE TITLE
Example of routes in app in not working

### ISSUE THREAD

**Issue by eloo** [cloudfoundry-community/terraform-provider-cf#236]
Hi,
it looks like the documentation is not updated for the app resource and its routes block.

When i try to use the example 
```
 routes = [
    { route = "${cloudfoundry_route.java-spring.id}" },
    { route = "${cloudfoundry_route.java-spring-2.id}" }
  ]
```
terraform is complaining like this
```
An argument named "routes" is not expected here. Did you mean to define a
block of type "routes"?
```

So can you please provider a proper example of the routes block in the app?
I guess for service binding this is also the case.

Thanks

**Comment by ArthurHlt** [comment]
Hi @eloo ,
This is more about terraform 0.12 syntax which is not allowing array for block type.
As your error says you should write like this:

```hcl
routes {
  route = "${cloudfoundry_route.java-spring.id}" 
}
routes {
  route = "${cloudfoundry_route.java-spring-2.id}"
}
```

**Comment by eloo** [comment]
@ArthurHlt 
Yes that is what i have found also.
But why have you closed the ticket? The documentation is still wrong in this repository

**Comment by innokenty** [comment]
Confirmed, new syntax works and `service_binding` is also affected indeed.
Docu should be updated.
