### ISSUE TITLE
OrgManager and SpaceManger should be able to set user roles

### ISSUE THREAD

**Issue by mogul** [cloudfoundry-community/terraform-provider-cf#240]
A Cloud Foundry user with only an OrgManager or SpaceManager role can run 
`cf set-org-role` and `cf set-space-role` on the the orgs and spaces where they have that role to set permissions for other users. 

However, it's **not** possible to  declare which accounts should have which roles on those orgs and spaces and use the Terraform provider (provisioned with the same account info) to make it so, even though you provide the same information.

Note we are using the [latest version of the provider](https://github.com/cloudfoundry-community/terraform-provider-cf/releases/tag/v0.11.0) and our CF API endpoint is reporting api version 2.146.0.

We've tried doing this two ways First, by specifying the users by name as you would at the command-line, eg
```
resource "cloudfoundry_space_users" "development" {
    space       = "${cloudfoundry_space.development.id}"
    developers  = ["joebob@organization.gov"]
}
```

When we do that, we see
<details>
  <summary>Show output</summary>

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place
Terraform will perform the following actions:
  ~ cloudfoundry_space_users.development
      developers.#:          "0" => "1"
      developers.2835520694: "" => "joebob@organization.gov"
Plan: 0 to add, 1 to change, 0 to destroy.
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.
  Enter a value: yes
cloudfoundry_space_users.development: Modifying... (ID: ff8dfb3c-8802-9eb5-e55a-7c2f4a6c2359)
  developers.#:          "0" => "1"
  developers.2835520694: "" => "joebob@organization.gov"
Error: Error applying plan:
1 error occurred:
	* cloudfoundry_space_users.development: 1 error occurred:
	* cloudfoundry_space_users.development: You are not authorized to perform the requested action
Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```
</details>

We've also tried by specifying it this way:
```
data "cloudfoundry_user" "joebob" {
    name="joebob@organization.gov"
}
resource "cloudfoundry_space_users" "development" {
    space       = "${cloudfoundry_space.development.id}"
    developers  = ["${data.cloudfoundry_user.joebob.id}"]
}
```

When we do that, we see the same as above.

**Comment by loafoe** [comment]
@mogul have you tried adding a list of `managers` to the `cloudfoundry_space_users`, specifically the user you are using to run the provider with? It looks like the development space only has developers and no managers so that may cause some permission failures. I've experienced to same with `cloudfoundry_routes` and have to add explicit `depends_on` in some cases.
