### ISSUE TITLE
Migrating app state from v2 to v3 seems broken

### ISSUE THREAD

**Issue by innokenty** [cloudfoundry-community/terraform-provider-cf#246]
I am migrating from provider version 0.9.9 to 0.11.0 and I think the issues that I see might be related to provider itself and not my code. I am able to reproduce it with both Terraform 0.11.14 and 0.12.23. I will try to keep it short, but it's hard to explain it without much detail, so please request additional info if needed.

### Issue №1
[`resource_cf_app_migrate.go:153`](https://github.com/cloudfoundry-community/terraform-provider-cf/blob/5b4b38ad7794fc59eff5dc5ba8bbba3a46e878db/cloudfoundry/resource_cf_app_migrate.go#L153)
```golang
147	result, err = reader.ReadField([]string{"route"})
	if err != nil { return is, err }
	if result.Exists {
152		oldRoute := getListOfStructs(result.Value)
153		if oldRoute[0]["default_route_mapping_id"].(string) != "" {
```

When I ran this for the first time, Terraform crashed entirely! In the crash.log I could see that the error originates in the line 153 above, because `oldRoute` is empty, but still its first element is accessed. I added debug logging and found out that despite array being empty, `result.Exists` still evaluates to true. 
```
2020-03-16T10:59:24.106Z [DEBUG] plugin.terraform-provider-cloudfoundry: 2020/03/16 10:59:24 [INFO] Found app Record State v2; migrating from v2 to v3
2020-03-16T10:59:24.107Z [DEBUG] plugin.terraform-provider-cloudfoundry: panic: runtime error: index out of range
2020-03-16T10:59:24.108Z [DEBUG] plugin.terraform-provider-cloudfoundry: 
2020-03-16T10:59:24.108Z [DEBUG] plugin.terraform-provider-cloudfoundry: goroutine 346 [running]:
2020-03-16T10:59:24.109Z [DEBUG] plugin.terraform-provider-cloudfoundry: github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry.migrateAppStateV2toV3(0xc0003bde50, 0x12f70a0, 0xc0004e26c0, 0xc0003110a0, 0xc00056a488, 0xc00055fa00)
2020-03-16T10:59:24.109Z [DEBUG] plugin.terraform-provider-cloudfoundry: 	/home/travis/gopath/src/github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/resource_cf_app_migrate.go:153 +0x197d
```

I think the code should be at least changed to check if the array is empty or not. Removing this if-condition works just fine, that's how I discovered a second problem down the execution path....

### Issue №2
[`migrate_bits.go:174`](https://github.com/cloudfoundry-community/terraform-provider-cf/blob/5b4b38ad7794fc59eff5dc5ba8bbba3a46e878db/cloudfoundry/migrate_bits.go#L174)
```golang
168	result, err = reader.ReadField([]string{"add_content"})
	if err != nil { return is, err }
	addContents := getListOfStructs(result.Value)
173	if len(addContents) > 0 {
174		return is, fmt.Errorf("add_content attribute can't be migrate, please fixeit in other way and remove from terraform.tfstate add_content attributes")
	}
```
I think it's wrong to fail on the presence of those fields. Since they are in the remote state — I can't really remove them easily, and the values there I also don't really need. `source` I do have under `path` already and `destination`... not sure, but I think it can also be omitted. 

Again, removed this code and the deploy worked  just fine after that!

### Conclusion
What are your thoughts on this? I could send a PR if that is the way to fix the problem in your opinion as well: adding array len check and simply ignoring add_content. In general these two issues make migration extremely not straightforward and even nearly impossible. They are also very hard to investigate, because you don't really see much info on what went wrong and specifically — on how you can potentially fix it. I am still not sure actually how to fix this, without changing provider source code. Maybe you can give me a tip?

**Comment by innokenty** [comment]
Added a PR 👆

**Comment by innokenty** [comment]
Added a PR 👆

**Comment by ArthurHlt** [comment]
fix by the PR thanks @innokenty
