### ISSUE TITLE
Add a blue green strategy

### ISSUE THREAD

**Issue by ArthurHlt** [cloudfoundry-community/terraform-provider-cf#25]
To implements blue green deployment, I see for now three different ways:
1. Use v3 api to do blue green deployment as explained [here](https://books.google.fr/books?id=NwglDwAAQBAJ&pg=PT388&lpg=PT388&dq=cloud+foundry+v3+blue+green+deployment&source=bl&ots=aXUH3uShDD&sig=3FMRlo7En8GdxuNU_d9nyzMklJ4&hl=fr&sa=X&ved=0ahUKEwi7-JKS9oXZAhUFtBQKHYbGCuUQ6AEIQzAD#v=onepage&q=cloud%20foundry%20v3%20blue%20green%20deployment&f=false) (this will actually leverage the point about getting app id)
2. In [Autopilot](https://github.com/contraband/autopilot) style, which is a straight forward approach by playing with multiple route attachment (like I did on https://github.com/orange-cloudfoundry/terraform-provider-cloudfoundry)
3. In [bluemix](https://github.com/bluemixgaragelondon/cf-blue-green-deploy) style, which is actually prepared on this provider (you can see it here: https://github.com/mevansam/terraform-provider-cf/blob/master/cloudfoundry/resource_cf_app.go#L219-L238 )

I like the first approach and actual v3 api give the ability this kind of thing (see app and droplets resources in [the v3 doc](http://v3-apidocs.cloudfoundry.org/version/3.37.0/index.html#set-current-droplet) but on older versions of cloud foundry this could not be available. 

In the third approach, have smoke test script is nice and can be also integrated with first approach.

The second one is, for me, a quick-win: easy to do and already experienced over https://github.com/orange-cloudfoundry/terraform-provider-cloudfoundry but doesn't implement smoke tests.

@mevansam @psycofdj Do you see other strategies ? What will a good approach for you ?

**Comment by samedguener** [comment]
Thanks for summing up the potential approaches of doing Blue/Green-Deployment.

I like the second approach, due to the fact it is simple to implement and easy to understand.

The first one is also very much appealing for me! But wouldn't it mean that we have to switch to v3 api, rather than using v2 alongside with v3?

In my PR [#22](https://github.com/mevansam/terraform-provider-cf/pull/22), I implemented it using multiple routes attachments as you mentioned in your second point. Furthermore I considered the following case:

If one runs an application A with 30 active instances and wants to update his application, the approach of adding the new application B with 30 instances and mapping the application to route is a no-go. The main reason is the resource-consumption of the 30 new instances of the application B.

In my approach I shutdown in a alternating way the instances, so the endpoint performance stays nearly the same and high resource-consumption is prohibited.

Best,
Samed

**Comment by gberche-orange** [comment]
thanks @samedguener for your contribution in #22 !

The core contributors (@mevansam @psycofdj @ArthurHlt )'s priority for getting native support for blue-green in the provider is currently low for the following reasons:
- our current priority is to cut the 1.0 release with stable/hardened models for existing features (see https://github.com/mevansam/terraform-provider-cf/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0 ) 
- zero downtime support is of higher priority than blue/green which adds additional rollback capabilities and associated complexity
   - the core CF teams are working on getting native zero-down-time, see initial thoughts at https://docs.google.com/document/d/116I_mOWjZcPeIbUvvsh-jAcwpoE_mGPD_SkCel5xXuU/edit#heading=h.ah2mu674txs8 and current active work in https://www.pivotaltracker.com/story/show/153455613 This has the potential to keep complexity in the provider as low as turning on a feature flag on the app/CF instance.

We're therefore iceboxing blue-green work in the provider for the short term.

We however welcome your contributions and involvement in the provider. Smaller issues/stories that align with the short term priorities may be an easier path for contributing to the provider, and joining the core contributors team.

**Comment by gberche-orange** [comment]
@lixilin2301 @jcarrothers-sap 

Zero downtime support in CAPI is now ready. See related https://github.com/cloudfoundry/cloud_controller_ng/blob/master/docs/v3/zero_downtime_deployments.md and associated CAPI epic at https://www.pivotaltracker.com/epic/show/3658601 Support in CF CLI is getting closer to GA. Relates to #120

**Comment by janosbinder** [comment]
Thanks @gberche-orange . I had a look, but it seems not all commercial provider supports this API. E.g. on SAP Cloud Platform:

**Comment by ArthurHlt** [comment]
The second solution has been implemented in #203 and also deal with possible new deployment strategy by design to let you choose between current strategy, blue-green strategy designed here and the new strategy provided by new cloud foundry.

see doc here for complete usage: https://github.com/cloudfoundry-community/terraform-provider-cf/blob/rework-back/website/docs/r/app.html.markdown
