### ISSUE TITLE
Feature request: cloudfoundry_service_instance create timeout as an argument

### ISSUE THREAD

**Issue by eatsan** [cloudfoundry-community/terraform-provider-cf#257]
Some service instance creations (i.e. MySQL Galera cluster from some service provider's catalog) can last more than 15 mins. Hard-coded create timeout defined in the cloud_foundry_service_instance resource fails with the following error: 

`Error: timeout while waiting for state to become 'succeeded' (last state: 'in progress', timeout: 15m0s)`

Optional argument `timeout` for the resource would give flexibility to user in case of long lasting service creation processes.

**Comment by janosbinder** [comment]
There is a timeout block already supported, where you can define something like 
```
 timeouts {
    create = "60m"
    delete = "2h"
  }
```

Search here for Operation Timeouts https://www.terraform.io/docs/configuration/resources.html

I am closing this issue now.
