### ISSUE TITLE
Error when authenticate on cf using username/password

### ISSUE THREAD

**Issue by fredrb** [cloudfoundry-community/terraform-provider-cf#264]
`terraform apply` sometimes yields error in authentication. I couldn't find any pattern to it, but sometimes I get the following error:

```
❯ terraform apply -auto-approve

Error: Error when creating clients: Error when authenticate on cf using username/password: Post https://login.cf.sap.hana.ondemand.com/oauth/token: dial tcp: i/o timeout
```

On second try usually works fine. 
I haven't tried in other Cloud Foundry environments other than SAP Cloud Platform. So it could be an issue on the platform side.

**Comment by janosbinder** [comment]
We use internally and very extensively this provider at SAP and we have not seen this issue. I would see some network configuration problem. Therefore I am closing it now.
