### ISSUE TITLE
Bug: destroy of cloudfoundry_service_broker fails if the broker target itself isn't available

### ISSUE THREAD

**Issue by mogul** [cloudfoundry-community/terraform-provider-cf#269]
GIVEN I have the following code in my `.tf` file:
```
data "cloudfoundry_space" "spaces" {
  for_each = {
    development = "development"
    staging     = "staging"
    production  = "prod"
  }
  name     = each.value
  org_name = "gsa-datagov"
}

resource cloudfoundry_service_broker "ssb-broker" {
  for_each = {
    development = "development"
    staging     = "staging"
    production  = "prod"
  }
  fail_when_catalog_not_accessible = true
  name                             = "ssb-${each.value}-${var.cf_username}"
  url                              = "https://${cloudfoundry_route.ssb_uri.endpoint}"
  username                         = random_uuid.client_username.result
  password                         = random_password.client_password.result
  space                            = data.cloudfoundry_space.spaces["${each.key}"].id
  depends_on = [
    cloudfoundry_app.ssb
  ]
}
```
AND the route `cloudfoundry_route.ssb_uri` is not bound to an application
WHEN I `terraform destroy`
THEN I should see all three `cloudfoundry_service_broker.ssb-broker[*]` get destroyed
AND I should see `cloudfoundry_route.ssb_uri` and other resources get destroyed
BUT instead I see
```
Error: Error when getting catalog signature: Status code: 404 Not Found, Body: 404 Not Found: Requested route ('epic-snail.app.cloud.gov') does not exist.

  on main.tf line 102, in resource "cloudfoundry_service_broker" "ssb-broker":
 102: resource cloudfoundry_service_broker "ssb-broker" {

Error: Error when getting catalog signature: Status code: 404 Not Found, Body: 404 Not Found: Requested route ('epic-snail.app.cloud.gov') does not exist.

  on main.tf line 102, in resource "cloudfoundry_service_broker" "ssb-broker":
 102: resource cloudfoundry_service_broker "ssb-broker" {

Error: Error when getting catalog signature: Status code: 404 Not Found, Body: 404 Not Found: Requested route ('epic-snail.app.cloud.gov') does not exist.

  on main.tf line 102, in resource "cloudfoundry_service_broker" "ssb-broker":
 102: resource cloudfoundry_service_broker "ssb-broker" {
```
AND the `terraform destroy` does not succeed

This might be related to the `fail_when_catalog_not_accessible` flag, but toggling it to `false` made no difference, and in any case the broker URL shouldn't be checked for availability during a destroy/`delete-service-broker` operation.

**Comment by ArthurHlt** [comment]
thanks for the report, you have actually this issue when terraform try to read information before applying your change on the flag `fail_when_catalog_not_accessible` that's why it fails even if you change it. The delete-service-broker as you may understand here, don't read the catalog.

You can actually fix that by modifying by hand the state to set `false` on `fail_when_catalog_not_accessible`, I know that is not great but there is no alternative when using `fail_when_catalog_not_accessible`

**Comment by ArthurHlt** [comment]
I've closed the issue but if you find or think there is a biggest problem feel free to reopen
