### ISSUE TITLE
Data source for provider shared domain

### ISSUE THREAD

**Issue by archgrove** [cloudfoundry-community/terraform-provider-cf#3]
There doesn't appear to be a way to get the shared domain(s) offered by a provider, as the domain datasource requires one to provide a name.

A `shared_domains` resource might be useful to solve this?

**Comment by gberche-orange** [comment]
@archgrove thanks for submitting this suggestion

the current [domain](https://github.com/mevansam/terraform-provider-cf/blob/master/website/docs/d/domain.html.markdown#argument-reference) data source indeed returns a single domain which needs to match at least one of `name` or  `domain` and `subdomain` attributes.

Would the following datasource below match your need ?

A new `domains` datasource with no argument and the following attributes
```
id - The GUID of the domain
name - The full domain name if not provided as an argument
domain- The part of the domain name if not provided as an argument
org - The org if this is a private domain owned by an org
shared_with_orgs - (array of String holding org GUIDs) If this is a private domain, the orgs to which the domain is [shared with](http://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html#sharing-private-domains)
```

**Comment by gberche-orange** [comment]
Could be inspired by https://www.terraform.io/docs/providers/aws/d/ami_ids.html or https://github.com/mevansam/terraform-provider-ldap/blob/master/website/docs/d/query.html.markdown#attributes-reference

**Comment by gberche-orange** [comment]
@archgrove any feedback ?

**Comment by archgrove** [comment]
Sorry @gberche-orange ; GitHub notifications eluded me. The suggested resource sounds interesting. If one could specify no domain, but specify the status and type information, I think it would work. To mirror the cfcli, with `cf domains`, I see:

```
name                                            status   type
cfapps.io                                       shared
cf-tcpapps.io                                   shared   tcp
apps.internal                                   shared
ourdomain.cfapps.io                                  owned
anotherdomain.com                                     owned
```

I'm keen to find `cfapps.io` (and possibly `apps.internal`, but that's less useful).

**Comment by ArthurHlt** [comment]
Please check new release at https://github.com/cloudfoundry-community/terraform-provider-cf/releases/tag/v0.10.0 to see if it fix your issue.
I'm closing it for now, please re-open if you still found on issue on this.
