### ISSUE TITLE
Move cfapi and repo package into a distinct repo

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-community/terraform-provider-cf#56]
This is a split of #38 and an [iceboxed pivotal tracker story](https://www.pivotaltracker.com/story/show/134896833)
- [ ] Collect pain points and thing about improvement suggestion to [CF CLI](https://github.com/cloudfoundry/cli/)
- [x] Submit an issue to CF CLI team to have the CLI CLI be more client-friendly and proposal for an official go-lang CF API repo
- [ ] Contribute back our code into the official go-lang CF API repo
- [ ] Remove cfapi and repo package in favor of contributed official go-lang CF API repo

**Comment by gberche-orange** [comment]
See related stories in CF CLI team backlog:

https://www.pivotaltracker.com/epic/show/3960386 extract CC and UAA API clients into their own packages
https://www.pivotaltracker.com/epic/show/2088038 CC API V3 support in CF CLI
https://www.pivotaltracker.com/story/show/153570873 GA the V3 commands

**Comment by gberche-orange** [comment]
@ArthurHlt @psycofdj @janosbinder have you considered https://github.com/cloudfoundry-community/go-cfclient ?

**Comment by gberche-orange** [comment]
Discussion hold with the Cf CLI team during Cf summit Basel office hours with @tjvman and @abbyachau 

Submitted related https://github.com/cloudfoundry/cli/issues/1481

**Comment by gberche-orange** [comment]
[CC API V2 deprecation draft plan](https://docs.google.com/document/d/1KFZogeeexOqFf13oKHloe2QAorLh9OqwQHp8JvBl9lY/edit) has been published. A 6 month overlap is planned by the time the CF CLI is not using CC API V2 anymore.

**Comment by ArthurHlt** [comment]
fixed on #203 but rely on a cloudfoundry cli fork: https://github.com/cloudfoundry-community/cloudfoundry-cli
