### ISSUE TITLE
cf_app support for specifying staging timeout

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-community/terraform-provider-cf#64]
See [cf_app](https://github.com/mevansam/terraform-provider-cf/blob/master/website/docs/r/app.html.markdown#argument-reference)
> * `timeout` - (Optional, Number) Defines the number of seconds that Cloud Foundry waits for starting your application.

w.r.t. CLI:
> cf push --help
> [...]
> ENVIRONMENT:
>    CF_STAGING_TIMEOUT=15        Max wait time for buildpack staging, in minutes
>    CF_STARTUP_TIMEOUT=5         Max wait time for app instance startup, in minutes
>

**Comment by ArthurHlt** [comment]
Please check new release at https://github.com/cloudfoundry-community/terraform-provider-cf/releases/tag/v0.10.0 to see if it fix your issue.
I'm closing it for now, please re-open if you still found on issue on this.
