### ISSUE TITLE
Implement cf_service_instance data source

### ISSUE THREAD

**Issue by psycofdj** [cloudfoundry-community/terraform-provider-cf#78]
This issue requests the implementation and documentation of the `cf_service_instance` data source.

Some work from @jcarrothers-sap is already available here: https://github.com/jcarrothers-sap/terraform-provider-cf/commit/627380022d1c21bea3ceb3ba4ecf8a2266642a6d

**Comment by ArthurHlt** [comment]
Please check new release at https://github.com/cloudfoundry-community/terraform-provider-cf/releases/tag/v0.10.0 to see if it fix your issue.
I'm closing it for now, please re-open if you still found on issue on this.
