### ISSUE TITLE
Complete isolation segment support 

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry-community/terraform-provider-cf#8]
Happy to send a patch if you'd be open to this.

**Comment by gberche-orange** [comment]
Hi @jmcarp, contribution on the IS support would be great (was discussed 

I understand @mevansam is currently working on preparing the acceptance test environment (on GCP) to move away from initial PCFDev based tests (which does not support IS), to upstream CF instance. This could then include prereqs for supporting IS CC API calls.

**Comment by gberche-orange** [comment]
@ArthurHlt and @mevansam planning to pair on this item next week. Once hashcorp integration testing is complete (which requires stability), this environnement will be rebuilt with one IS and other features enabled (e.g. C2C)

**Comment by gberche-orange** [comment]
Following exchange with @psycofdj, here are limitations of #125 that could be addressed in a second PR:
* [ ] add support for setting org default isolation segment. To avoid cyclic dependencies (between `org` and `isolation-segment-entitlement`, and `isolation-segment` resources), this would be added into a distinct `isolation-segment-association` resource (that follows the `*-association` pattern in the [AWS provider](https://www.terraform.io/docs/providers/aws/index.html))
   * The workaround is to assign each space managed by TF explicitly to an isolation segment. Spaces created in a self service maner may require that the enclosing org get modified manually outside terraform.
* [ ] add support for importing a "cloudfoundry_isolation_segment_entitlement" resource
   * The workaround is to manually import the existing entitlements into the TF state 
* [ ] Refine test coverage acceptance test coverage for 
   * the cloudfoundry_isolation_segment_entitlement resource as to avoid future regressions (i.e. similar to testAccCheckSegmentExists() and testAccCheckSegmentDestroyed() functions)
   * the space isolation segment assignment 

@jmcarp please review if #125 suits your needs and whether you'd be interested in contribution some of the remaining steps above

**Comment by gberche-orange** [comment]
#125 added a large part of the isolation support, thanks to @psycofdj !

I renamed this issue to be able to track the remaining associated work.

**Comment by ArthurHlt** [comment]
Please check new release at https://github.com/cloudfoundry-community/terraform-provider-cf/releases/tag/v0.10.0 to see if it fix your issue.
I'm closing it for now, please re-open if you still found on issue on this.
